### ISSUE TITLE
Add feature: label show up on non user value changes.

### ISSUE THREAD

**Issue by armata99** [hearsilent/DiscreteSlider#12]
Hi.
It will be very nice if You add modes for label such as showing up on setting values from code (like 
when attaching it to scroll listeners) or showing up when pressed.
Let me know how are Your thoughts on this.

**Comment by hearsilent** [comment]
Hi @someAndroidDeveloper 
So you want setting value from code, showing the value label? Maybe 3s?

**Comment by armata99** [comment]
Yes but I think 1.5s would be optimum for it, or its much better if you define a setter for that too.
The other thing came to my mind on this subject is that You setting these modes as flags so people can combine the attributes like this example Im giving:

`app:ds_labelMode="showOnPressHold | showOnProgressChange"`

These are the two which Im looking for, You may like to add `hidden` or other behaviors as well. 
Its gonna give Your code a good advantage.

**Comment by hearsilent** [comment]
@someAndroidDeveloper I've released new version 1.2.0, you can try now!

**Comment by armata99** [comment]
@hearsilent I've got it running.

-the duration is ok.
-show on press hold not working
-and for the other option this happens.
![sample](https://user-images.githubusercontent.com/53018491/79011993-8670fe00-7b7a-11ea-8d4e-222d051f74ec.png)

FYI: currently it's on `showOnPressHold | showOnProgressChange` or the mode 3 according to Your tutorial. I tried them in both xml and java, got same results.
You can also use a secondary seekbar to trigger the one you testing, just in case you wondering ;)

**Comment by hearsilent** [comment]
@someAndroidDeveloper Can you provide sample code to reproduce this?

**Comment by armata99** [comment]
@hearsilent Sure, here is the simplest way. I tried to simulate the value change using a secondary slider:

XML:
````xml
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:clipChildren="false"
    tools:context=".MainActivity">

    <hearsilent.discreteslider.DiscreteSlider
        android:id="@+id/main_slider"
        android:layout_width="wrap_content"
        android:layout_height="470dp"
        android:layout_gravity="center_vertical"
        app:ds_inactiveTrackColor="#D3D3D3"
        app:ds_orientation="vertical"
        app:ds_thumbColor="@color/colorPrimary"
        app:ds_thumbPressedColor="#1F089CF7"
        app:ds_thumbRadius="9dp"
        app:ds_trackColor="#D3D3D3"
        app:ds_valueLabelDuration="2500"
        app:ds_valueLabelMode="showOnProgressChange|showOnPressHold" />

    <hearsilent.discreteslider.DiscreteSlider
        android:id="@+id/test_slider"
        android:layout_width="wrap_content"
        android:layout_height="470dp"
        android:layout_gravity="center_vertical|end"
        app:ds_inactiveTrackColor="#D3D3D3"
        app:ds_orientation="vertical"
        app:ds_thumbColor="@color/colorPrimary"
        app:ds_thumbPressedColor="#1F089CF7"
        app:ds_thumbRadius="9dp"
        app:ds_trackColor="#D3D3D3"
        app:ds_valueLabelMode="none" />
</FrameLayout>
````
and the Java:
````java
import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.util.Log;

import hearsilent.discreteslider.DiscreteSlider;

public class MainActivity extends AppCompatActivity{

    private DiscreteSlider mainSlider,testSlider;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        mainSlider=findViewById(R.id.main_slider);
        testSlider=findViewById(R.id.test_slider);

        mainSlider.setCount(200);
        testSlider.setCount(200);
        mainSlider.setMinProgress(1);
        testSlider.setMinProgress(1);

        testSlider.setOnValueChangedListener(sliderListener);
    }

    private DiscreteSlider.OnValueChangedListener sliderListener=new DiscreteSlider.OnValueChangedListener(){
        @Override
        public void onValueChanged(int progress, boolean fromUser) {
            super.onValueChanged(progress, fromUser);
            mainSlider.setProgress(progress);
            Log.d("slider change: ","value: "+progress);
        }
    };
}
````
and again the result:

![Screenshot_1586948736](https://user-images.githubusercontent.com/53018491/79330466-d6f7ab00-7f2e-11ea-91c3-b7743deb1756.png)

The listener you have provided gets called once you release the thumb so make sure to drag it at least twice to see what I see.

**Comment by hearsilent** [comment]
@someAndroidDeveloper I've fixed this issue, and release the version `1.2.1`.

**Comment by armata99** [comment]
@hearsilent 
It works good for me.
About the other option: it's still not working.
The current issue is the bubble should show up when you hold the thumb (not dragging it) but it doesn't till You drag it for a bit.

**Comment by hearsilent** [comment]
@someAndroidDeveloper You can call `setValueChangedImmediately(true)` when setup slider.

**Comment by armata99** [comment]
@hearsilent I called it before setting the listener as You mentioned in docs
unfortunately it didn't work.

**Comment by hearsilent** [comment]
@someAndroidDeveloper It's must be called in right slider (Your touching slider)

**Comment by armata99** [comment]
@hearsilent I understand it, and I did so. but the thing that I suspect is me explaining what I mean incorrectly.
Can You please tell me the simple logic behind the label popup so I could figure out whats missing?

**Comment by hearsilent** [comment]
@someAndroidDeveloper Only can sync by step now. I'll try to implement method to provide sync immediately.

**Comment by armata99** [comment]
@hearsilent so far so good. I'll be waiting
